-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."finproDimDate"
(
    dateid integer,
    date date,
    day integer,
    month integer,
    monthname character varying,
    quarter integer,
    year integer,
    weekday character varying,
    weeknumber integer,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."finproDimBranches"
(
    branchid integer,
    branchcode character varying,
    brancname character varying,
    cityid integer,
    countryid integer,
    PRIMARY KEY (branchid)
);

CREATE TABLE IF NOT EXISTS public."finproDimCities"
(
    cityid integer,
    cityname character varying,
    state character varying,
    countryid integer,
    PRIMARY KEY (cityid)
);

CREATE TABLE IF NOT EXISTS public."finproDimCountries"
(
    countryid integer,
    countryname character varying,
    countrycode character,
    continent character varying,
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."finproDimAccountTypes"
(
    accounttypeid integer,
    accounttype character varying,
    PRIMARY KEY (accounttypeid)
);

CREATE TABLE IF NOT EXISTS public."finproDimCustomers"
(
    customerid integer,
    customername character varying,
    email character varying,
    dateofbirth date,
    accounttypeid integer,
    branchid integer,
    countryid integer,
    PRIMARY KEY (customerid)
);

CREATE TABLE IF NOT EXISTS public."finproFactTransactions"
(
    transactionid integer,
    dateid integer,
    customerid integer,
    branchid integer,
    accounttypeid integer,
    transactionamount numeric(10, 2),
    transactiontype character varying,
    PRIMARY KEY (transactionid)
);

ALTER TABLE IF EXISTS public."finproDimBranches"
    ADD FOREIGN KEY (cityid)
    REFERENCES public."finproDimCities" (cityid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproDimBranches"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."finproDimCountries" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproDimCities"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."finproDimCountries" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproDimCustomers"
    ADD FOREIGN KEY (accounttypeid)
    REFERENCES public."finproDimAccountTypes" (accounttypeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproDimCustomers"
    ADD FOREIGN KEY (branchid)
    REFERENCES public."finproDimBranches" (branchid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproDimCustomers"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."finproDimCountries" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproFactTransactions"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."finproDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproFactTransactions"
    ADD FOREIGN KEY (customerid)
    REFERENCES public."finproDimCustomers" (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproFactTransactions"
    ADD FOREIGN KEY (branchid)
    REFERENCES public."finproDimBranches" (branchid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."finproFactTransactions"
    ADD FOREIGN KEY (accounttypeid)
    REFERENCES public."finproDimAccountTypes" (accounttypeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;